### ISSUE TITLE
appium.dmg 1.4.13 has bad symlinks

### ISSUE THREAD

**Issue by scastria** [appium/appium-dot-app#512]
Inside the Contents of appium.dmg are symlinks to node modules pointing to /usr/local/lib/node_modules instead of ../submodules:

lrwxr-xr-x 1 shawn admin 38 Oct 8 09:22 appium-adb -> /usr/local/lib/node_modules/appium-adb
lrwxr-xr-x 1 shawn admin 40 Oct 8 09:20 appium-atoms -> /usr/local/lib/node_modules/appium-atoms
drwxr-xr-x@ 17 shawn admin 578 Oct 8 09:09 appium-chromedriver
lrwxr-xr-x 1 shawn admin 46 Oct 8 09:20 appium-instruments -> /usr/local/lib/node_modules/appium-instruments
drwxr-xr-x@ 14 shawn admin 476 Jul 21 03:27 appium-support
lrwxr-xr-x 1 shawn admin 41 Oct 8 09:20 appium-uiauto -> /usr/local/lib/node_modules/appium-uiauto

**Comment by mgehlen** [comment]
i corrected them with a very stupid script, but so far it seems to work and is a throwaway anyways, maybe it is useful for someone:

````
cd /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules

rm appium-adb 
ln -s ../submodules/appium-adb

rm appium-atoms
ln -s ../submodules/appium-atoms


rm appium-instruments
ln -s ../submodules/appium-instruments

rm appium-uiauto

ln -s ../submodules/appium-uiauto

cd $HOME
```

**Comment by anshu1987** [comment]
@mgehlen : I have tried the above the script but didn't help me , getting the same  uncaughtException: Cannot find module 'appium-instruments' error.
Is it working for you if yes then is there any other setting need to perform.?

**Comment by anshu1987** [comment]
@scastria I just downloaded the new dmg from appium download location but that issue still exists.

**Comment by mgehlen** [comment]
@anshu1987 yes, it worked for me. I Test in real device, maybe that is the difference? Simulator does not work for me for quite some time.

**Comment by JuanMaCuevas** [comment]
Thanks @mgehlen your solution worked for me using the Version 1.4.13 (Draco)

**Comment by seleniumbheema** [comment]
@JuanMaCuevas @mgehlen 
what exactly we need to do here?

**Comment by seleniumbheema** [comment]
it not working fine, Appium server starts fine, once i run the code, it pop up with window saying instruments cannot be opened because of a problem

same issue is not getting, when I run the appium through terminal which I;ve install with Ruby.this issue is only for APpium GUI

**Comment by mgehlen** [comment]
@seleniumbheema considering your last comment, did you successfully run the lines from my comment? If not this is how you can do it:

1. open terminal
2. copy each line from my post into the terminal and press enter

or

wrap the lines in a shell script.

After that it worked for me (Appium 1.4.13 GUI version, the non-GUIs on my Jenkins work fine anyways, they did not need the script)

**Comment by seleniumbheema** [comment]
@ mgehlen Thanks it works fine now, but Appium 1.4.13, GUI version working fine but now, when try to run the code with Iphone 6simulator 9.0 and iphone 6 real device 8.1.1, pop's up window saying Instruments can not be opened  or Instruments crashed

**Comment by samiramin** [comment]
@mgehlen  I am using GUI app and I tried to execute the above commands.
Its not working for me. show error "rm: appium-adb: is a directory"
how can I execute the commands.

**Comment by scastria** [comment]
cd /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules

and then do a ls -l and send us the output.  If the contents of this directory are NOT symlinks but instead real directories, then you would get that error.  But they should be symlinks which means you can remove them.

**Comment by penguinho** [comment]
I've made the changes and uploaded a new DMG, if you redownload it should work. It may take 24 hours for the new DMG to get into the CDN

**Comment by anshu1987** [comment]
After downloading the new dmg getting and executing it on real iPhone Device with iOS 9.1 getting the below error message:

aunching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --safari --browser-name "Safari" --udid "7af59e51658e4a887f59c6ffece549c6611093c2" --show-ios-log --default-device --launch-timeout "200000"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Configuring Safari session

info: [debug] Using local .zip from command line: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session

error: Could not pre-launch appium: Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'

**Comment by samiramin** [comment]
@scastria
Sams-MacBook-Pro:node_modules samiramin$ ls -l
total 0
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 adm-zip
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 appium-adb
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 appium-atoms
drwxr-xr-x@ 27 samiramin  admin   918 Jul 21 13:57 appium-chromedriver
drwxr-xr-x@ 15 samiramin  admin   510 Jul 21 13:57 appium-instruments
drwxr-xr-x@ 14 samiramin  admin   476 Jul 21 13:57 appium-support
drwxr-xr-x@ 15 samiramin  admin   510 Apr 19  2015 appium-uiauto
drwxr-xr-x@ 15 samiramin  admin   510 Jul 21 13:57 appium-xcode
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 argparse
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 assert
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 async
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bdd-with-opts
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 binary-cookies
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 body-parser
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bplist-creator
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 bplist-parser
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bufferpack
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 bytes
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 camel-back-promise
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 chai
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 chai-as-promised
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 colors
drwxr-xr-x@ 13 samiramin  admin   442 Jul 21 13:57 date-utils
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 difflib
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 es6-promise
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 express
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 glob
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gps-demo-app
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 grunt
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 grunt-cli
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-contrib-jshint
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 grunt-exec
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-jscs-checker
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-mocha-test
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 grunt-newer
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 gulp
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 gulp-jscs
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gulp-jshint
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gulp-util
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 js-yaml
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 js2xmlparser2
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 jshint-stylish
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 longjohn
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 md5calculator
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 merge-stream
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 method-override
drwxr-xr-x@ 11 samiramin  admin   374 Jul 21 13:57 mkdirp
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 mocha
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 mocha-jenkins-reporter
drwxr-xr-x@ 19 samiramin  admin   646 Mar 19  2015 monocle-js
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 morgan
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 mv
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 namp
drwxr-xr-x@ 10 samiramin  admin   340 Apr 19  2015 ncp
drwxr-xr-x@ 10 samiramin  admin   340 Apr 19  2015 node-idevice
drwxr-xr-x@ 12 samiramin  admin   408 Jul 21 13:57 node-simctl
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 node-static
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 node-uuid
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 npmlog
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 path
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 plist
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 promisepipe
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 prompt
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 q
drwxr-xr-x@ 17 samiramin  admin   578 Mar 19  2015 request
drwxr-xr-x@ 13 samiramin  admin   442 Apr 19  2015 rewire
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 rimraf
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 run-sequence
drwxr-xr-x@ 10 samiramin  admin   340 May  3 12:28 safari-launcher
drwxr-xr-x@  9 samiramin  admin   306 May 11 14:30 sample-apps
drwxr-xr-x@  7 samiramin  admin   238 Jul 21 13:57 sandboxed-module
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 saucelabs
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 serve-favicon
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 sinon
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 sinon-chai
drwxr-xr-x@ 12 samiramin  admin   408 Jul 21 13:57 socket.io
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 socket.io-client
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 socks
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 spawn-mocha-parallel
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 split
drwxr-xr-x@  8 samiramin  admin   272 Apr 19  2015 stack-trace
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 swig
drwxr-xr-x@ 14 samiramin  admin   476 Jul 21 13:57 temp
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 through
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 touch
drwxr-xr-x@  9 samiramin  admin   306 Apr 19  2015 udidetect
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 uncolor
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 underscore
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 underscore-cli
drwxr-xr-x@ 73 samiramin  admin  2482 Mar 19  2015 underscore.string
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 unorm
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 unzip
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 utf7
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 uuid-js
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 vargs
drwxr-xr-x@ 17 samiramin  admin   578 Mar 19  2015 wd
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 wd-bridge
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 which
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 win-spawn
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 winston
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 ws
drwxr-xr-x@ 23 samiramin  admin   782 Jul 21 13:57 xml2js
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 xmldom
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 xpath
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 yargs
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 yiewd

**Comment by samiramin** [comment]
@scastria 

Sams-MacBook-Pro:node_modules samiramin$ ls -l
total 0
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 adm-zip
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 appium-adb
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 appium-atoms
drwxr-xr-x@ 27 samiramin  admin   918 Jul 21 13:57 appium-chromedriver
drwxr-xr-x@ 15 samiramin  admin   510 Jul 21 13:57 appium-instruments
drwxr-xr-x@ 14 samiramin  admin   476 Jul 21 13:57 appium-support
drwxr-xr-x@ 15 samiramin  admin   510 Apr 19  2015 appium-uiauto
drwxr-xr-x@ 15 samiramin  admin   510 Jul 21 13:57 appium-xcode
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 argparse
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 assert
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 async
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bdd-with-opts
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 binary-cookies
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 body-parser
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bplist-creator
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 bplist-parser
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 bufferpack
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 bytes
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 camel-back-promise
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 chai
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 chai-as-promised
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 colors
drwxr-xr-x@ 13 samiramin  admin   442 Jul 21 13:57 date-utils
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 difflib
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 es6-promise
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 express
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 glob
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gps-demo-app
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 grunt
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 grunt-cli
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-contrib-jshint
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 grunt-exec
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-jscs-checker
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 grunt-mocha-test
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 grunt-newer
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 gulp
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 gulp-jscs
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gulp-jshint
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 gulp-util
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 js-yaml
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 js2xmlparser2
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 jshint-stylish
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 longjohn
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 md5calculator
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 merge-stream
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 method-override
drwxr-xr-x@ 11 samiramin  admin   374 Jul 21 13:57 mkdirp
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 mocha
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 mocha-jenkins-reporter
drwxr-xr-x@ 19 samiramin  admin   646 Mar 19  2015 monocle-js
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 morgan
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 mv
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 namp
drwxr-xr-x@ 10 samiramin  admin   340 Apr 19  2015 ncp
drwxr-xr-x@ 10 samiramin  admin   340 Apr 19  2015 node-idevice
drwxr-xr-x@ 12 samiramin  admin   408 Jul 21 13:57 node-simctl
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 node-static
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 node-uuid
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 npmlog
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 path
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 plist
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 promisepipe
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 prompt
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 q
drwxr-xr-x@ 17 samiramin  admin   578 Mar 19  2015 request
drwxr-xr-x@ 13 samiramin  admin   442 Apr 19  2015 rewire
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 rimraf
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 run-sequence
drwxr-xr-x@ 10 samiramin  admin   340 May  3 12:28 safari-launcher
drwxr-xr-x@  9 samiramin  admin   306 May 11 14:30 sample-apps
drwxr-xr-x@  7 samiramin  admin   238 Jul 21 13:57 sandboxed-module
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 saucelabs
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 serve-favicon
drwxr-xr-x@ 16 samiramin  admin   544 Mar 19  2015 sinon
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 sinon-chai
drwxr-xr-x@ 12 samiramin  admin   408 Jul 21 13:57 socket.io
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 socket.io-client
drwxr-xr-x@  5 samiramin  admin   170 Mar 19  2015 socks
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 spawn-mocha-parallel
drwxr-xr-x@ 10 samiramin  admin   340 Mar 19  2015 split
drwxr-xr-x@  8 samiramin  admin   272 Apr 19  2015 stack-trace
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 swig
drwxr-xr-x@ 14 samiramin  admin   476 Jul 21 13:57 temp
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 through
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 touch
drwxr-xr-x@  9 samiramin  admin   306 Apr 19  2015 udidetect
drwxr-xr-x@ 11 samiramin  admin   374 Mar 19  2015 uncolor
drwxr-xr-x@  8 samiramin  admin   272 Jul 21 13:57 underscore
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 underscore-cli
drwxr-xr-x@ 73 samiramin  admin  2482 Mar 19  2015 underscore.string
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 unorm
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 unzip
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 utf7
drwxr-xr-x@  8 samiramin  admin   272 Mar 19  2015 uuid-js
drwxr-xr-x@  6 samiramin  admin   204 Mar 19  2015 vargs
drwxr-xr-x@ 17 samiramin  admin   578 Mar 19  2015 wd
drwxr-xr-x@ 13 samiramin  admin   442 Mar 19  2015 wd-bridge
drwxr-xr-x@  9 samiramin  admin   306 Jul 21 13:57 which
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 win-spawn
drwxr-xr-x@ 14 samiramin  admin   476 Mar 19  2015 winston
drwxr-xr-x@ 10 samiramin  admin   340 Jul 21 13:57 ws
drwxr-xr-x@ 23 samiramin  admin   782 Jul 21 13:57 xml2js
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 xmldom
drwxr-xr-x@  7 samiramin  admin   238 Mar 19  2015 xpath
drwxr-xr-x@  9 samiramin  admin   306 Mar 19  2015 yargs
drwxr-xr-x@ 12 samiramin  admin   408 Mar 19  2015 yiewd

**Comment by scastria** [comment]
That is not what is inside the 1.4.13 dmg that I installed. However, according to the previous post, the new dmg should have the symlinks fixed now.

**Comment by samiramin** [comment]
@scastria Its lists for version 1.4.8.
I have updated dmg as penguinho just updated it.
It has following files.

total 32
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 adm-zip
lrwxr-xr-x   1 samiramin  admin    24 Oct 26 21:53 appium-adb -> ../submodules/appium-adb
lrwxr-xr-x   1 samiramin  admin    26 Oct 26 21:53 appium-atoms -> ../submodules/appium-atoms
drwxr-xr-x@ 17 samiramin  admin   578 Oct 12 16:01 appium-chromedriver
lrwxr-xr-x   1 samiramin  admin    32 Oct 26 21:53 appium-instruments -> ../submodules/appium-instruments
drwxr-xr-x@ 14 samiramin  admin   476 Oct 12 16:01 appium-support
lrwxr-xr-x   1 samiramin  admin    27 Oct 26 21:53 appium-uiauto -> ../submodules/appium-uiauto
drwxr-xr-x@ 15 samiramin  admin   510 Oct 12 16:01 appium-xcode
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 argparse
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 assert
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 async
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 bdd-with-opts
drwxr-xr-x@ 16 samiramin  admin   544 Oct 12 16:01 binary-cookies
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 body-parser
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 bplist-creator
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 bplist-parser
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 bufferpack
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 bytes
drwxr-xr-x@  5 samiramin  admin   170 Oct 12 16:01 camel-back-promise
drwxr-xr-x@ 16 samiramin  admin   544 Oct 12 16:01 chai
drwxr-xr-x@  5 samiramin  admin   170 Oct 12 16:01 chai-as-promised
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 colors
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 date-utils
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 difflib
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 es6-promise
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 express
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 glob
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 gps-demo-app
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 grunt
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 grunt-cli
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 grunt-contrib-jshint
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 grunt-exec
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 grunt-jscs-checker
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 grunt-mocha-test
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 grunt-newer
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 gulp
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 gulp-jscs
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 gulp-jshint
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 gulp-util
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 js-yaml
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 js2xmlparser2
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 jshint-stylish
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 longjohn
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 md5calculator
drwxr-xr-x@  6 samiramin  admin   204 Oct 12 16:01 merge-stream
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 method-override
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 mkdirp
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 mocha
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 mocha-jenkins-reporter
drwxr-xr-x@ 19 samiramin  admin   646 Oct 12 16:01 monocle-js
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 morgan
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 mv
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 namp
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 ncp
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 node-idevice
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 node-simctl
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 node-static
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 node-uuid
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 npmlog
drwxr-xr-x@  6 samiramin  admin   204 Oct 12 16:01 path
drwxr-xr-x@ 14 samiramin  admin   476 Oct 12 16:01 plist
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 promisepipe
drwxr-xr-x@ 14 samiramin  admin   476 Oct 12 16:01 prompt
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 q
drwxr-xr-x@ 17 samiramin  admin   578 Oct 12 16:01 request
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 rewire
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 rimraf
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 run-sequence
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 safari-launcher
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 sample-apps
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 sandboxed-module
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 saucelabs
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 serve-favicon
drwxr-xr-x@ 16 samiramin  admin   544 Oct 12 16:01 sinon
drwxr-xr-x@  5 samiramin  admin   170 Oct 12 16:01 sinon-chai
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 socket.io
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 socket.io-client
drwxr-xr-x@  5 samiramin  admin   170 Oct 12 16:01 socks
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 spawn-mocha-parallel
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 split
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 stack-trace
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 swig
drwxr-xr-x@ 14 samiramin  admin   476 Oct 12 16:01 temp
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 through
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 touch
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 udidetect
drwxr-xr-x@ 11 samiramin  admin   374 Oct 12 16:01 uncolor
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 underscore
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 underscore-cli
drwxr-xr-x@ 73 samiramin  admin  2482 Oct 12 16:01 underscore.string
drwxr-xr-x@  6 samiramin  admin   204 Oct 12 16:01 unorm
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 unzip
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 utf7
drwxr-xr-x@  8 samiramin  admin   272 Oct 12 16:01 uuid-js
drwxr-xr-x@  6 samiramin  admin   204 Oct 12 16:01 vargs
drwxr-xr-x@ 17 samiramin  admin   578 Oct 12 16:01 wd
drwxr-xr-x@ 13 samiramin  admin   442 Oct 12 16:01 wd-bridge
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 which
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 win-spawn
drwxr-xr-x@ 14 samiramin  admin   476 Oct 12 16:01 winston
drwxr-xr-x@ 10 samiramin  admin   340 Oct 12 16:01 ws
drwxr-xr-x@ 23 samiramin  admin   782 Oct 12 16:01 xml2js
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 xmldom
drwxr-xr-x@  7 samiramin  admin   238 Oct 12 16:01 xpath
drwxr-xr-x@  9 samiramin  admin   306 Oct 12 16:01 yargs
drwxr-xr-x@ 12 samiramin  admin   408 Oct 12 16:01 yiewd


That also has an issue(while running with xcode 7.1 appium 1.4.13), It shows 
could not load inserted library "InstrumentsShim.dylib" because no suitable image found.

So I added "--native-instruments-lib" custom server flags in Developer setttings. 
Now It works fine.

**Comment by darekzborowski** [comment]
I was having the exact same problem with latest Appium and xcode 7.1

Uninstalled and Installed Xcode 7.1 again.
Uninstalled, Downloaded and installed Appium 1.4.13.
Added --native-insturments-lib to developer settings.

Works now. Thank you very much for your help.

**Comment by KashishAggarwal** [comment]
Hi @scastria ,

I rum below command, but facing error" No such file or directory",,, Actually Everything works fine for me with Appium v1.4.13 and Xcode 7.0.1 and IOSSimulator6 version 8.1, but I perform Appium reset and after that I am unable to launch Appum Server, so i was going thru this post and run this command  ""cd /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules""""" but facing error"No such file directory"

Please help !!!!

**Comment by anshu1987** [comment]
@KashishAggarwal : Use the below mentioned solution provided by @mgehlen :
cd /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules

rm appium-adb 
ln -s ../submodules/appium-adb

rm appium-atoms
ln -s ../submodules/appium-atoms


rm appium-instruments
ln -s ../submodules/appium-instruments

rm appium-uiauto

ln -s ../submodules/appium-uiauto

cd $HOME

It will solve your problem.

**Comment by anshu1987** [comment]
@darekzborowski : Did you got any safari launcher error with Appium 1.4.13 latest dmg.I am getting the same error as mentioned above.

aunching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --safari --browser-name "Safari" --udid "7af59e51658e4a887f59c6ffece549c6611093c2" --show-ios-log --default-device --launch-timeout "200000"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: **** NEW SESSION ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Configuring Safari session

info: [debug] Using local .zip from command line: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session

error: Could not pre-launch appium: Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
